### ISSUE TITLE
识别貌似不准?

### ISSUE THREAD

**Issue by ViCrack** [gh0stkey/avList#5]
![图片](https://user-images.githubusercontent.com/18179821/110228243-88823f00-7f3a-11eb-9f2a-d5c7704ee951.png)
![图片](https://user-images.githubusercontent.com/18179821/110228248-959f2e00-7f3a-11eb-93dc-812713d97c6c.png)

上面的进程名是火绒的吧
是不是写重复了

**Comment by gh0stkey** [comment]
不好意思，没注意，之前做测试的时候遇到了天融信这个终端，后来想了想突然想起来天融信终端防御就是把火绒换了个皮，感谢指出问题。
