### ISSUE TITLE
部分规则问题

### ISSUE THREAD

**Issue by Geidalaodicha** [gh0stkey/avList#8]
1. 在已有的rule中，这两条：
```
"gov_defence_service.exe": "云锁",
"gov_defence_daemon.exe": "云锁",
``` 

应该是网防 G01。

2. 360 total security (360国际版) 的进程：
```
QHActiveDefense.exe 
QHWatchdog.exe 
QHSafeTray.exe 
QHSafeMain.exe 
```
![image](https://user-images.githubusercontent.com/29503873/118388240-d19af180-b655-11eb-94dd-9b8a8d93fe43.png)
![image](https://user-images.githubusercontent.com/29503873/118388256-dfe90d80-b655-11eb-8154-ab0d2d356c1a.png)

**Comment by gh0stkey** [comment]
网防G01就是拿的云锁改的，所以直接采用了云锁这个名字，360国际版进程这就同步更新，感谢！！！
